### PR TITLE
completed two column challenge

### PR DESCRIPTION
**Pull request by NolanReda**
two column

### CODE REVIEW

**Comment by NolanReda** [comment]
two column

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Nolan! A few notes:
1. Your line spacing on the subheader in the first row and the text in the second row is too small as compared to the example.
2. The columns in the second row are slightly misaligned from center.
3. The casing of the text in the button is incorrect

Please revise and submit a new screenshot with your revision.

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Yo dude! I see that this is still in progress, just submitting a review so that I know when this is ready for feedback 🤓

**Comment by NolanReda** [comment]
two column fix

**Review by codingcodymiller — APPROVED** [review]
Nice work!!

**Pull request merged**
