### PR TITLE
completed brochure challenge

### PR DESCRIPTION
**Pull request by NolanReda**
brochure form

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Nolan! A few notes:
1. You don't have any space between the form control elements, but the example has some vertical space between each form control.
2. Your last label is wrapping to a new line, but the example does not.
3. Your form is too narrow as compared to the example.

Please revise and submit a new screenshot with your revision.

**Comment by NolanReda** [comment]
brochure changes

**Comment by NolanReda** [comment]
The text wrapping actually came about because I narrowed down the viewport to work on everything on one screen. I widened it and it was all good.

**Review by codingcodymiller — APPROVED** [review]
Nice work!!

**Pull request merged**
